create sequence cliente_seq start 1 increment 1;
create sequence estoque_seq start 1 increment 1;
create sequence item_estoque_seq start 1 increment 1;
create sequence item_seq start 1 increment 1;
create sequence pedido_seq start 1 increment 1;
create sequence produto_seq start 1 increment 1;
create sequence reposical_seq start 1 increment 1;
create table cliente (id int8 not null, nome varchar(255), primary key (id));
create table estoque (id int8 not null, primary key (id));
create table item (id int8 not null, quantidade int8, pedido_id int8 not null, produto_id int8 not null, primary key (id));
create table item_estoque (id int8 not null, quantidade int8, estoque_id int8 not null, produto_id int8 not null, primary key (id));
create table pedido (id int8 not null, status varchar(255), cliente_id int8 not null, primary key (id));
create table produto (id int8 not null, nome varchar(255), valor float8, primary key (id));
create table reposicao (id int8 not null, status varchar(255), primary key (id));
alter table item add constraint pedido_id foreign key (pedido_id) references pedido;
alter table item add constraint produto_id foreign key (produto_id) references produto;
alter table item_estoque add constraint estoque_id foreign key (estoque_id) references estoque;
alter table item_estoque add constraint produto_id foreign key (produto_id) references produto;
alter table pedido add constraint cliente_id foreign key (cliente_id) references cliente;
